### ISSUE TITLE
Very slow rendering of a small GRIB file

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#18]
https://t.co/iamnxajML8

I am struggling to render this file. I think it is a problem with NODATA value.

**Comment by PeterPetrik** [comment]
Dataset has around 1 milion of cells. 

I think the problem may simply be with the data flow in MDAL->QGIS (related to https://github.com/lutraconsulting/MDAL/issues/13), since now all the data is duplicated in the memory and we do not filter it by extent. 

definitely slower than in Crayfish and worth of investigation.

**Comment by PeterPetrik** [comment]
closing, this is QGIS issue
