### ISSUE TITLE
Not detecting velocity arrows

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#19]
See ticket #18 for sample data. 
NB: Crayfish does show the velocity arrows.

**Comment by PeterPetrik** [comment]
It is correctly detected, the problem was that this file contains just 1 timestep and there was a bug in the QGIS mesh layer in that case. fixed with https://github.com/qgis/QGIS/pull/7430/commits/232449987a692c2c5806f28565233bc2a7781539
![screenshot_20180718_154315](https://user-images.githubusercontent.com/804608/42885701-f810a1b2-8aa1-11e8-851c-9a175ecbf127.png)
