### ISSUE TITLE
Mesh calculator - xdmf file

### ISSUE THREAD

**Issue by qqplot1988** [lutraconsulting/MDAL#242]
There is a problem with the **mesh calculator** for centered element. When I'm calculating the max of all time step, it makes the result in the new group but doesn't create à .dat file. Is there any solution for this? When I save the project, close it and reopen: the group diseapears.

It will be great if we can create isocontour from the results on the mesh file for example (as for raster for example).

**Comment by saberraz** [comment]
For the first part of your question: what version of QGIS are you using. There should be support now for cell centred elements in mesh calculator. Feel free to attach an example file, so that we can replicate the issue.

For the second part of your question, you need to install Crayfish plugin. Then you will find algorithms to convert your mesh to vector/raster:
![Screenshot_20200403_070448](https://user-images.githubusercontent.com/2649047/78329435-9c2e6400-7579-11ea-84c6-694cf87c64b5.png)
