### ISSUE TITLE
Support telemac outputs

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#31]

**Comment by PeterPetrik** [comment]
- [Serafin files](http://www.gdal.org/drv_selafin.html): Outputs of the TELEMAC 2D hydrodynamic modelling package

**Comment by saberraz** [comment]
Maybe @patricev can help?

**Comment by ccoulet** [comment]
Hi guys
I started to work on the selafin (or serafin) driver to support Telemac in mdal.
I think I could know read a mesh but unfortunately, I was not able to test it in QGIS...
I compile on windows with mingw and obtain a file libmdal.dll which is, I suppose, my version of mdalprovider.dll
But when replacing the original version by mine in QGIS, I have a message saying that the module loading failed (specified module not found)
Am I missing something?
Regards

**Comment by saberraz** [comment]
@ccoulet that sounds very promising!

You need also to build QGIS without internal mdal (-D WITH_INTERNAL_MDAL=FALSE).

If you do a PR on what you have, I can give it a try....

**Comment by ccoulet** [comment]
I didn't planned to build QGIS...
And I think it will take time to build it on my Windows computer...
I will probably try first on a Linux one, this will be probably easier...
In the mean time I forked MDAL on https://github.com/Artelia/MDAL and create a branch Telemac in order to let you test it...
Maybe it will be simpler if you create a Telemac branch on the MDAL repository in which I could commit my update...

**Comment by saberraz** [comment]
Managed to compile it successful (telemac branch) but get error when trying to open this file:
[baxter_SS_hotstart.slf.zip](https://github.com/lutraconsulting/MDAL/files/2920340/baxter_SS_hotstart.slf.zip)

(worth adding a small test file too).

**Comment by ccoulet** [comment]
Thanks for the feed back. Any error message?
I added a slf directory in test with a mesh file in it
I have a problem in the compilation of gmock which fail so cannot work on a test

**Comment by PeterPetrik** [comment]
Hi @ccoulet , when you will have some working code (ideally with a small test file in tests/data/ and test_telemac.cpp), please do pull request and I will review the code. Thanks for contribution!

As Saber mentioned, you need to compile QGIS yourself without internal MDAL to be able to test it in QGIS.

**Comment by ccoulet** [comment]
Hi @PeterPetrik and @saberraz 
Is there a solution for you to share with me a QGIS version without internal MDAL? I don't have too much time and compiling QGIS seems a little be complex as I never done it before.
Otherwise, @saberraz could you report me the error you encountered during your first test. Maybe I will be able to see what I've done wrong
Thanks in advance
Regards

**Comment by PeterPetrik** [comment]
@ccoulet you can compile mdalinfo command line tool and try to load the file with that one. I think it would be worth to compile QGIS for you, I do not see easy way to share development version with you.

**Comment by ccoulet** [comment]
@PeterPetrik thanks for the tips.
I just compile it and could test with a windows error so I could try to debug.

**Comment by ccoulet** [comment]
Hi Guys
I updated the telemac branch on Artelia/Mdal.
I know have a positive result when using mdalinfo.
Hope this will works on your side.
Thanks for your feedback

**Comment by saberraz** [comment]
Hi @ccoulet 
I built your branch and still QGIS does not recognise the format. But as you said, I get result from mdalinfo.

- SLF is not listed as a type of mesh.
- There are a lot of warnings when building mdal from slf part of the code.

**Comment by PeterPetrik** [comment]
@ccoulet can you please create pull request from your branch to MDAL? I am happy to add comments to the code and review it?

Please verify that your code follows https://github.com/lutraconsulting/MDAL#coding-standards--contribution
